FROM nvcr.io/nvidia/l4t-base:r32.5.0

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /home/yoloopencvdnn

# install prerequisites
RUN apt-get update && apt-get install -y build-essential cmake gcc g++ gdb clang rsync tar python3-dev libatlas-base-dev gfortran libhdf5-serial-dev hdf5-tools && apt-get clean
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN pip install numpy

COPY . .
RUN bash install_opencv_jetson.sh